// Package story defines the domain model for a long-form script (seed,
// bible, chapters, quality scores) and the mechanical validators that check
// generated content without calling an LLM.
package story

import (
	"fmt"
	"strings"
	"time"
)

type Seed struct {
	Profession, Epistemology, RecordType  string
	ProtagonistSex                        string // male|female
	Antagonist, WeakAlly, HumiliationType string
	Betrayal                              string
	Duration                              int // years between the humiliation and the reckoning
	WrittenOverreach, ObjectContainer     string
	LegacyArtifact, ReckoningPlace        string
	EndingType                            string
	Region                                string // drives the name pool and town flavor
	// Attire is the narrator's work clothing, resolved once at seed-draw
	// time from configs/professions.yaml (config.Profession.Attire) — not
	// generated by any LLM, and not the same thing as the bible's
	// appearance fields (Person.Build/Hair/FaceNote), which describe the
	// person, not what they're wearing. Flows through to the avatar
	// module's portrait prompt via internal/export.BundleNarrator.
	Attire string
}

// Person covers both the narrator ("name, age, profession, city" per the
// brief) and cast members ("name, age, role, one physical tic") — one type
// with a superset of fields rather than two near-identical structs.
//
// Sex/Build/Hair/FaceNote are appearance fields the avatar module's
// portrait prompt needs — generated by the bible LLM call alongside
// everything else, narrator-only in practice (cast members leave them
// empty; nothing reads them there). Sex is generated as part of the same
// JSON shape for consistency but is always overwritten from
// Seed.ProtagonistSex after parsing (see internal/generate/bible.go) —
// that's already a hard seed constraint, not something to leave to the
// model's judgment.
type Person struct {
	Name        string `json:"name"`
	Age         int    `json:"age"`
	Role        string `json:"role"` // "narrator", "antagonist", "weak_ally", ...
	City        string `json:"city,omitempty"`
	Profession  string `json:"profession,omitempty"`
	PhysicalTic string `json:"physical_tic,omitempty"`
	Sex         string `json:"sex,omitempty"`
	Build       string `json:"build,omitempty"`     // slight | average | sturdy
	Hair        string `json:"hair,omitempty"`      // color, length, how it's worn
	FaceNote    string `json:"face_note,omitempty"` // one concrete detail, not a list
}

type Event struct {
	Year int    `json:"year"`
	What string `json:"what"`
}

type Bible struct {
	Narrator      Person            `json:"narrator"`
	Cast          []Person          `json:"cast"`
	Timeline      []Event           `json:"timeline"`
	FamilyLaw     string            `json:"family_law"`
	RefrainPhrase string            `json:"refrain_phrase"`
	SeededLine    string            `json:"seeded_line"`
	Numbers       map[string]string `json:"numbers"`
}

// ForChapters returns a copy of b with the narrator's appearance fields
// (Build/Hair/FaceNote) cleared. Those exist solely for the avatar module's
// portrait prompt, never for chapter prose — every chapter-generation LLM
// call must use this, not b directly, or the model reliably works the
// glasses/hairstyle/scar into first-person narration, repeated across the
// script. Sex is left untouched: chapters need it for pronoun consistency.
func (b Bible) ForChapters() Bible {
	b.Narrator.Build = ""
	b.Narrator.Hair = ""
	b.Narrator.FaceNote = ""
	return b
}

// Full returns b unchanged — the counterpart to ForChapters, named so call
// sites that need every field (chiefly the manifest.json export the avatar
// module reads) say so explicitly instead of just passing script.Bible bare.
func (b Bible) Full() Bible {
	return b
}

type Chapter struct {
	Index       int    `json:"index"`
	Beat        string `json:"beat"` // "hook", "the_cut", "the_demand", ... from chapters.yaml
	TargetWords int    `json:"target_words"`
	Text        string `json:"text"`         // TTS-ready: numbers spelled out, no "$"
	DisplayText string `json:"display_text"` // normal formatting, for export/reading
	Summary     string `json:"summary"`      // ~80 words, generated separately
}

type QualityScores struct {
	HookStrength        float64 `json:"hook_strength"`
	ProfessionCausality float64 `json:"profession_causality"`
	Restraint           float64 `json:"restraint"`
	SceneNotSummary     float64 `json:"scene_not_summary"`
	PlantingPayoff      float64 `json:"planting_payoff"`
	RefusalPresent      float64 `json:"refusal_present"`
	AISmell             float64 `json:"ai_smell"` // 10 = reads natural/human, 0 = obviously generated
	Comment             string  `json:"comment"`
}

func (q QualityScores) Mean() float64 {
	return (q.HookStrength + q.ProfessionCausality + q.Restraint + q.SceneNotSummary +
		q.PlantingPayoff + q.RefusalPresent + q.AISmell) / 7
}

func (q QualityScores) Min() float64 {
	m := q.HookStrength
	for _, v := range [...]float64{
		q.ProfessionCausality, q.Restraint, q.SceneNotSummary,
		q.PlantingPayoff, q.RefusalPresent, q.AISmell,
	} {
		if v < m {
			m = v
		}
	}
	return m
}

type Status string

const (
	StatusPending  Status = "pending"
	StatusAccepted Status = "accepted"
	StatusRejected Status = "rejected"
	// StatusAcceptedWithWarnings means the whole-script repetition-guard
	// validation (runScriptValidation) never fully converged within its
	// round budget — the script is still kept and counted as a real
	// result (it skips cross-script dedup and review, see finishPipeline),
	// not thrown away after real money was already spent generating and
	// repairing it. "warnings" refers to unresolved mechanical violations
	// (a repeated phrase, a placement rule), not narrative quality — a
	// human should skim it before publishing, review never ran on it.
	StatusAcceptedWithWarnings Status = "accepted_with_warnings"
)

type Script struct {
	ID        string
	CreatedAt time.Time
	Seed      Seed
	Bible     Bible
	Title     string
	Chapters  []Chapter
	Quality   QualityScores
	Status    Status
	WordCount int
	Provider  string
	Model     string
	TokensIn  int
	TokensOut int
	// Usage is the per-(role, provider, model) cost breakdown — `gen
	// stats` reads this to show where the bill actually went (e.g. most
	// of it as thinking tokens on chapter generation, not review), which
	// TokensIn/TokensOut alone can't distinguish.
	Usage []UsageEntry
}

// CauseInitial and CauseRepair are UsageEntry.Cause's two values.
// CauseInitial is the first-pass sequential chapter generation (and the
// one-time bible/continuity-check calls); CauseRepair is anything spent
// fixing a violation after the fact (continuity fixes, the repetition
// guard's point-fixes and full regenerations, review's weak-chapter
// regeneration, cross-script dedup). Splitting these out is what makes
// "how much did REPAIR cost versus CREATION" a real number instead of a
// guess — a script that fails validation after many rounds can spend most
// of its budget on repair without ever becoming sellable.
const (
	CauseInitial = "initial"
	CauseRepair  = "repair"
)

// UsageEntry aggregates every LLM call sharing one (Role, Provider, Model,
// Cause) quadruple. Role is one of "generate", "summary", "review",
// "continuity".
type UsageEntry struct {
	Role           string
	Provider       string
	Model          string
	Cause          string
	Calls          int
	TokensIn       int
	TokensOut      int
	ThinkingTokens int // already included in TokensOut; broken out for cost-by-cause reporting
}

// RecordUsage folds one LLM call into both the running totals
// (TokensIn/TokensOut/Provider) and the finer-grained Usage breakdown.
// This is the single place a call's cost gets attributed — callers should
// never update TokensIn/TokensOut directly. cause should be CauseInitial
// or CauseRepair.
func (s *Script) RecordUsage(role, provider, model string, tokensIn, tokensOut, thinkingTokens int, cause string) {
	s.TokensIn += tokensIn
	s.TokensOut += tokensOut
	if provider != "" {
		s.Provider = provider
	}

	for i := range s.Usage {
		u := &s.Usage[i]
		if u.Role == role && u.Provider == provider && u.Model == model && u.Cause == cause {
			u.Calls++
			u.TokensIn += tokensIn
			u.TokensOut += tokensOut
			u.ThinkingTokens += thinkingTokens
			return
		}
	}
	s.Usage = append(s.Usage, UsageEntry{
		Role: role, Provider: provider, Model: model, Cause: cause, Calls: 1,
		TokensIn: tokensIn, TokensOut: tokensOut, ThinkingTokens: thinkingTokens,
	})
}

// RecomputeWordCount sets WordCount from the current Chapters' TTS text —
// the one source of truth, never trusted from the LLM's own count.
func (s *Script) RecomputeWordCount() {
	n := 0
	for _, c := range s.Chapters {
		n += len(strings.Fields(c.Text))
	}
	s.WordCount = n
}

// FullText joins every chapter's TTS text in chapter order, blank-line
// separated — the shape internal/review (which judges prose quality and
// genuinely needs the real text) and, when Settings.FullContext is true,
// internal/continuity send to the LLM. internal/story's cross-chapter
// validators scan this too.
func (s *Script) FullText() string {
	parts := make([]string, len(s.Chapters))
	for i, c := range s.Chapters {
		parts[i] = c.Text
	}
	return strings.Join(parts, "\n\n")
}

// SummaryText joins every chapter's short summary in chapter order,
// blank-line separated, prefixed with its chapter number — a much smaller
// stand-in for FullText that internal/continuity uses by default
// (Settings.FullContext false). Continuity's job is factual (names,
// numbers, timeline), not literary, and summaries already carry those
// facts — a real run showed one FullText-based continuity call alone cost
// $0.14 (28K input tokens, 95% of its output spent on thinking the model
// judged the full script's reasoning surface warranted); this cuts that
// surface down to roughly a tenth the size.
func (s *Script) SummaryText() string {
	parts := make([]string, len(s.Chapters))
	for i, c := range s.Chapters {
		parts[i] = fmt.Sprintf("Chapter %d (%s): %s", c.Index, c.Beat, c.Summary)
	}
	return strings.Join(parts, "\n\n")
}

// ChapterByIndex finds a chapter by its 1-based Index, for targeted
// regeneration (continuity fixes, `gen regenerate --chapter N`).
func (s *Script) ChapterByIndex(index int) (*Chapter, bool) {
	for i := range s.Chapters {
		if s.Chapters[i].Index == index {
			return &s.Chapters[i], true
		}
	}
	return nil, false
}
